// AI 프롬프트 퀴즈 - 문제 데이터 (테스트용 초안: 초급 5 + 중급 5)

const QUIZ_DATA = {
  beginner: [
    {
      id: "b1",
      category: "이미지",
      original: {
        type: "image",
        caption: "어둡고 배경에 잡동사니가 많은 음식 사진",
      },
      promptParts: [
        { text: "이 음식 사진을 " },
        { blank: 0 },
        { text: " 보정해 주세요.\n배경의 " },
        { blank: 1 },
        { text: "는 정리하고,\n음식의 종류와 양은 " },
        { blank: 2 },
        { text: " 주세요." },
      ],
      blanks: [
        { id: 0, answer: "밝고 따뜻하게" },
        { id: 1, answer: "잡동사니" },
        { id: 2, answer: "그대로 유지해" },
      ],
      distractors: ["어둡고 차갑게", "음식을 더 많이 보이게", "모두 삭제해"],
      result: {
        type: "bullets",
        title: "결과",
        items: ["사진이 밝고 따뜻해짐", "배경이 깔끔해짐", "음식 종류와 양은 원본과 동일"],
      },
      learningPoint: "바꿀 것 + 제거할 것 + 유지할 것을 구체적으로 말하기",
    },
    {
      id: "b2",
      category: "문서 작성",
      original: {
        type: "text",
        caption: "회의록 (A4 2장 분량 · 발췌)",
        lines: [
          "1. 신규 교육 프로그램 관련 논의",
          "   - 다양한 의견 교환 후 신규 교육 일정을 9월 3주차로 확정함",
          "2. 홍보 관련 논의",
          "   - 홍보자료 제작 필요성 공감, 담당자로 홍보팀 지정",
          "3. 기타 논의",
          "   - 예산 관련 후속 논의 필요",
          "   - 다음 회의 날짜를 10월 첫째 주로 결정",
          "(이하 생략 — 총 A4 2장 분량)",
        ],
      },
      promptParts: [
        { text: "다음 회의록을 " },
        { blank: 0 },
        { text: "해 주세요.\n핵심 내용은 " },
        { blank: 1 },
        { text: "개로 정리하고,\n결과는 " },
        { blank: 2 },
        { text: "로 보여 주세요." },
      ],
      blanks: [
        { id: 0, answer: "요약" },
        { id: 1, answer: "3" },
        { id: 2, answer: "불릿 형식" },
      ],
      distractors: ["번역", "20", "소설 형식"],
      result: {
        type: "bullets",
        title: "회의 핵심 내용",
        items: ["신규 교육 일정 확정", "홍보자료 제작 담당자 지정", "다음 회의 날짜 결정"],
      },
      learningPoint: "작업 + 분량 + 출력형식을 지정하면 결과가 명확해짐.",
    },
    {
      id: "b3",
      category: "일상",
      original: {
        type: "bullets",
        caption: "조건 카드",
        items: ["친구 2명", "서울에서 점심", "1인 예산 15,000원", "여러 곳을 비교하고 싶음"],
      },
      promptParts: [
        { text: "서울에서 친구 2명과 갈 수 있는\n" },
        { blank: 0 },
        { text: " 식당을 찾아주세요.\n예산은 " },
        { blank: 1 },
        { text: "이고,\n점심 식당 " },
        { blank: 2 },
        { text: "를 추천해 주세요." },
      ],
      blanks: [
        { id: 0, answer: "가성비 좋은" },
        { id: 1, answer: "1인 15,000원 이하" },
        { id: 2, answer: "3곳" },
      ],
      distractors: ["최고급", "1인 100,000원 이상", "30곳"],
      result: {
        type: "table",
        title: "결과",
        headers: ["식당", "예상 가격", "특징"],
        rows: [
          ["A식당", "12,000원", "한식"],
          ["B식당", "14,000원", "파스타"],
          ["C식당", "13,000원", "덮밥"],
        ],
      },
      learningPoint: "AI에게 추천을 받을 때는 조건을 구체적으로 제시하기.",
    },
    {
      id: "b4",
      category: "AI 기능",
      original: {
        type: "image-table",
        caption: "매출 숫자가 들어 있는 표 이미지",
        headers: ["월", "매출"],
        rows: [
          ["1월", "120"],
          ["2월", "145"],
          ["3월", "170"],
        ],
      },
      promptParts: [
        { text: "첨부한 이미지 속 " },
        { blank: 0 },
        { text: "를 읽고,\n내용을 " },
        { blank: 1 },
        { text: "해 주세요.\n결과는 다시 " },
        { blank: 2 },
        { text: "로 정리해 주세요." },
      ],
      blanks: [
        { id: 0, answer: "표" },
        { id: 1, answer: "텍스트로 추출" },
        { id: 2, answer: "표 형태" },
      ],
      distractors: ["사람 얼굴", "모두 삭제", "이야기 형식"],
      result: {
        type: "table",
        title: "결과",
        headers: ["월", "매출"],
        rows: [
          ["1월", "120"],
          ["2월", "145"],
          ["3월", "170"],
        ],
      },
      learningPoint: "AI는 글만 쓰는 것이 아니라 이미지 속 정보도 읽고 구조화할 수 있음.",
    },
    {
      id: "b5",
      category: "업무",
      original: {
        type: "bullets",
        caption: "행사 메모",
        items: [
          "행사명: 학부모 AI 체험교육",
          "날짜: 9월 15일",
          "장소: 교육관",
          "대상: 학부모",
          "신청 마감: 9월 10일",
        ],
      },
      promptParts: [
        { text: "다음 내용을 바탕으로\n학부모 대상 행사 안내문을 " },
        { blank: 0 },
        { text: " 작성해 주세요.\n문체는 " },
        { blank: 1 },
        { text: " 하고,\n행사 일정은 " },
        { blank: 2 },
        { text: " 주세요." },
      ],
      blanks: [
        { id: 0, answer: "친절하게" },
        { id: 1, answer: "쉽고 부드럽게" },
        { id: 2, answer: "빠짐없이 포함해" },
      ],
      distractors: ["어렵게", "전문용어 중심으로", "모두 빼"],
      result: {
        type: "text",
        title: "결과",
        lines: [
          "안녕하세요.",
          "학부모님을 위한 AI 체험교육이 9월 15일 교육관에서 진행됩니다.",
          "참여를 희망하시는 분은 9월 10일까지 신청해 주세요.",
        ],
      },
      learningPoint: "같은 정보라도 대상과 문체를 지정하면 표현이 달라짐.",
    },
  ],

  intermediate: [
    {
      id: "m1",
      category: "이미지",
      original: {
        type: "image",
        caption: "SNS 홍보용으로 사용하려는 음식 사진",
        items: ["배경 복잡", "음식 색감 어두움", "음식의 종류와 양은 변경하면 안 됨"],
      },
      promptParts: [
        { text: "이 사진을 " },
        { blank: 0 },
        { text: " 이미지처럼 보정해 주세요.\n전체 색감은 " },
        { blank: 1 },
        { text: " 만들고,\n배경은 " },
        { blank: 2 },
        { text: " 정리해 주세요.\n음식의 종류와 양은 " },
        { blank: 3 },
        { text: " 주세요." },
      ],
      blanks: [
        { id: 0, answer: "SNS 홍보용" },
        { id: 1, answer: "밝고 따뜻하게" },
        { id: 2, answer: "깔끔하게" },
        { id: 3, answer: "그대로 유지해" },
      ],
      distractors: ["증명사진용", "차갑고 어둡게", "더 복잡하게", "자유롭게 변경해"],
      result: {
        type: "text",
        title: "결과",
        locked: true,
        lines: ["밝고 따뜻한 홍보용 음식 이미지가 표시됨."],
      },
      learningPoint: "이미지 프롬프트에는 목적 + 변경사항 + 유지조건이 함께 들어가야 함.",
    },
    {
      id: "m2",
      category: "문서 작성",
      original: {
        type: "bullets",
        caption: "교육 결과보고 초안",
        items: [
          "참가자 35명",
          "만족도 평균 4.6점",
          "실습 시간이 부족하다는 의견 8건",
          "다음 과정에서는 실습 시간을 확대할 필요가 있음",
        ],
      },
      promptParts: [
        { text: "당신은 " },
        { blank: 0 },
        { text: "입니다.\n다음 교육 결과를 바탕으로\n" },
        { blank: 1 },
        { text: " 중심의 결과보고서를 작성해 주세요.\n결과는 " },
        { blank: 2 },
        { text: "으로 구성하고,\n문체는 " },
        { blank: 3 },
        { text: " 유지해 주세요." },
      ],
      blanks: [
        { id: 0, answer: "교육 결과보고서 작성 보조자" },
        { id: 1, answer: "주요 성과와 개선점" },
        { id: 2, answer: "제목·요약·개선사항" },
        { id: 3, answer: "공식적이고 간결하게" },
      ],
      distractors: ["여행 작가", "개인 감상", "자유시", "재미있는 인터넷 말투로"],
      result: {
        type: "text",
        title: "결과",
        locked: true,
        lines: [
          "[교육 결과 요약]",
          "참가자 35명이 참여했으며 만족도는 평균 4.6점으로 높게 나타났다.",
          "",
          "[개선사항]",
          "실습 시간 부족 의견이 확인되어 향후 과정에서는 실습 비중을 확대할 필요가 있다.",
        ],
      },
      learningPoint: "중급부터 역할 + 목적 + 출력형식 + 문체를 함께 설계함.",
    },
    {
      id: "m3",
      category: "일상",
      original: {
        type: "bullets",
        caption: "가족여행 조건",
        items: [
          "부모 2명",
          "초등학생 1명",
          "부산 1박 2일",
          "너무 많은 이동은 피하고 싶음",
          "관광과 식사를 함께 계획",
        ],
      },
      promptParts: [
        { text: "당신은 " },
        { blank: 0 },
        { text: "입니다.\n부모 2명과 초등학생 1명이 함께하는\n부산 1박 2일 여행을 계획해 주세요.\n일정은 " },
        { blank: 1 },
        { text: " 구성하고,\n관광지와 " },
        { blank: 2 },
        { text: "를 함께 포함해 주세요.\n결과는 " },
        { blank: 3 },
        { text: "로 정리해 주세요." },
      ],
      blanks: [
        { id: 0, answer: "가족여행 플래너" },
        { id: 1, answer: "이동이 무리하지 않게" },
        { id: 2, answer: "식사 장소" },
        { id: 3, answer: "시간대별 일정표" },
      ],
      distractors: ["논문 심사위원", "최대한 빡빡하게", "회사 회의", "소설 형식"],
      result: {
        type: "schedule",
        title: "결과",
        locked: true,
        heading: "1일차",
        items: [
          ["09:00", "부산역"],
          ["10:00", "감천문화마을"],
          ["12:00", "점심"],
          ["14:00", "해운대"],
          ["17:00", "숙소 체크인"],
        ],
      },
      learningPoint: "복잡한 요청에서는 상황·조건·출력형식을 같이 넣어야 함.",
    },
    {
      id: "m4",
      category: "AI 기능",
      original: {
        type: "bullets",
        caption: "프로젝트 회의 PDF",
        items: ["담당자", "해야 할 업무", "마감일", "아직 담당자가 정해지지 않은 항목 있음"],
      },
      promptParts: [
        { text: "첨부한 PDF를 읽고\n" },
        { blank: 0 },
        { text: "만 추출해 주세요.\n각 업무는 " },
        { blank: 1 },
        { text: " 기준으로 정리하고,\n결과는 " },
        { blank: 2 },
        { text: " 형식으로 보여 주세요.\n정보가 확인되지 않는 항목은 " },
        { blank: 3 },
        { text: " 주세요." },
      ],
      blanks: [
        { id: 0, answer: "해야 할 업무" },
        { id: 1, answer: "담당자와 마감일" },
        { id: 2, answer: "체크리스트" },
        { id: 3, answer: "임의로 추정하지 말고 표시해" },
      ],
      distractors: ["모든 조사 배경", "글자 수", "장편 보고서", "적당히 만들어"],
      result: {
        type: "checklist",
        title: "결과",
        locked: true,
        items: [
          "홍보물 제작 / 김OO / 9월 8일",
          "참가자 명단 작성 / 박OO / 9월 10일",
          "장소 확인 / 담당자 미정 / 9월 11일",
        ],
      },
      learningPoint: "AI에게 모르는 정보를 임의로 만들지 않도록 제약할 수 있음.",
    },
    {
      id: "m5",
      category: "업무",
      original: {
        type: "bullets",
        caption: "행사 기본자료",
        items: [
          "행사명: 주민 AI 체험교실",
          "대상: 지역 주민",
          "일정: 10월 20일",
          "교육내용: AI 이미지 제작, 문서 작성",
          "신청: 온라인 접수",
          "카드뉴스 제작 필요",
        ],
      },
      promptParts: [
        { text: "당신은 " },
        { blank: 0 },
        { text: "입니다.\n다음 행사 정보를 활용해\n지역 주민 대상 카드뉴스 초안을 작성해 주세요.\n내용은 " },
        { blank: 1 },
        { text: " 중심으로 구성하고,\n전체는 " },
        { blank: 2 },
        { text: "으로 만들어 주세요.\n각 장의 문장은 " },
        { blank: 3 },
        { text: " 작성하고,\n전문용어는 " },
        { blank: 4 },
        { text: " 주세요." },
      ],
      blanks: [
        { id: 0, answer: "공공기관 홍보 콘텐츠 기획자" },
        { id: 1, answer: "행사 핵심정보와 참여방법" },
        { id: 2, answer: "6장" },
        { id: 3, answer: "짧고 이해하기 쉽게" },
        { id: 4, answer: "최소화해" },
      ],
      distractors: ["소설가", "기관 내부 행정절차", "30장", "최대한 길게", "많이 사용해"],
      result: {
        type: "cardnews",
        title: "결과",
        locked: true,
        cards: [
          "AI, 어렵지 않아요!",
          "지역 주민 AI 체험교실",
          "AI 이미지 만들기",
          "AI로 문서 작성하기",
          "10월 20일 진행",
          "온라인으로 신청하세요",
        ],
      },
      learningPoint: "업무 프롬프트에서는 대상·목적·구조·제약조건이 중요함.",
    },
  ],
};
